//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webNews.Language.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webNews.Language.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy cập bị từ chối!.
        /// </summary>
        public static string Access_Denied_Lang {
            get {
                return ResourceManager.GetString("Access_Denied_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐỊa chỉ.
        /// </summary>
        public static string Address_Lang {
            get {
                return ResourceManager.GetString("Address_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Btn_Add_Lang {
            get {
                return ResourceManager.GetString("Btn_Add_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phê duyệt.
        /// </summary>
        public static string Btn_Approve_Lang {
            get {
                return ResourceManager.GetString("Btn_Approve_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở lại.
        /// </summary>
        public static string Btn_Back_Lang {
            get {
                return ResourceManager.GetString("Btn_Back_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Btn_Cancel_Lang {
            get {
                return ResourceManager.GetString("Btn_Cancel_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Btn_Close_Lang {
            get {
                return ResourceManager.GetString("Btn_Close_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string Btn_Complete_Lang {
            get {
                return ResourceManager.GetString("Btn_Complete_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Btn_Delete_Lang {
            get {
                return ResourceManager.GetString("Btn_Delete_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string Btn_Edit_Lang {
            get {
                return ResourceManager.GetString("Btn_Edit_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất ra Excel.
        /// </summary>
        public static string Btn_ExportExcel_Lang {
            get {
                return ResourceManager.GetString("Btn_ExportExcel_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string Btn_Print_Lang {
            get {
                return ResourceManager.GetString("Btn_Print_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả hàng.
        /// </summary>
        public static string Btn_Refund_Lang {
            get {
                return ResourceManager.GetString("Btn_Refund_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string Btn_Reject_Lang {
            get {
                return ResourceManager.GetString("Btn_Reject_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở phiếu.
        /// </summary>
        public static string Btn_ReOpen_Lang {
            get {
                return ResourceManager.GetString("Btn_ReOpen_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm lại.
        /// </summary>
        public static string Btn_Reset_Lang {
            get {
                return ResourceManager.GetString("Btn_Reset_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Btn_Save_Lang {
            get {
                return ResourceManager.GetString("Btn_Save_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Btn_Send {
            get {
                return ResourceManager.GetString("Btn_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu tạm.
        /// </summary>
        public static string Btn_Temp_Save_Lang {
            get {
                return ResourceManager.GetString("Btn_Temp_Save_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capchar lỗi!.
        /// </summary>
        public static string Captcharinvalid_Lang {
            get {
                return ResourceManager.GetString("Captcharinvalid_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn khách hàng.
        /// </summary>
        public static string ChooseCustomer_Lang {
            get {
                return ResourceManager.GetString("ChooseCustomer_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn danh mục(F2).
        /// </summary>
        public static string ChooseProduct_Lang {
            get {
                return ResourceManager.GetString("ChooseProduct_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhà cung cấp.
        /// </summary>
        public static string ChooseProvider_Lang {
            get {
                return ResourceManager.GetString("ChooseProvider_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phiếu tự tăng.
        /// </summary>
        public static string CodeAutoGen_Lang {
            get {
                return ResourceManager.GetString("CodeAutoGen_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string Contact_Information {
            get {
                return ResourceManager.GetString("Contact_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Detail_Lang {
            get {
                return ResourceManager.GetString("Detail_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Edit_Lang {
            get {
                return ResourceManager.GetString("Edit_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email_Lang {
            get {
                return ResourceManager.GetString("Email_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error_Lang {
            get {
                return ResourceManager.GetString("Error_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong qua trình xử lý!.
        /// </summary>
        public static string Errororequest_Lang {
            get {
                return ResourceManager.GetString("Errororequest_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File quá giới hạn dung lượng cho phép!.
        /// </summary>
        public static string File_exceeded_upload_capacity_Lang {
            get {
                return ResourceManager.GetString("File_exceeded_upload_capacity_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string FullName_Lang {
            get {
                return ResourceManager.GetString("FullName_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử giao dịch.
        /// </summary>
        public static string HistoryPayment_Lang {
            get {
                return ResourceManager.GetString("HistoryPayment_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử nhập hàng.
        /// </summary>
        public static string HistoryPayment1_Lang {
            get {
                return ResourceManager.GetString("HistoryPayment1_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nợ cần trả.
        /// </summary>
        public static string HistoryPayment2_Lang {
            get {
                return ResourceManager.GetString("HistoryPayment2_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện ảnh.
        /// </summary>
        public static string Image_Gallery {
            get {
                return ResourceManager.GetString("Image_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ở bản đồ lớn hơn.
        /// </summary>
        public static string In_Larger_Map {
            get {
                return ResourceManager.GetString("In_Larger_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu về công ty.
        /// </summary>
        public static string Introduction_Title {
            get {
                return ResourceManager.GetString("Introduction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin không hợp lệ!.
        /// </summary>
        public static string InvalidInfomation_Lang {
            get {
                return ResourceManager.GetString("InvalidInfomation_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực đầu tư.
        /// </summary>
        public static string Investment_Title {
            get {
                return ResourceManager.GetString("Investment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị khóa!.
        /// </summary>
        public static string LockedAccount_Lang {
            get {
                return ResourceManager.GetString("LockedAccount_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi sảy ra!.
        /// </summary>
        public static string Message_Error_Lang {
            get {
                return ResourceManager.GetString("Message_Error_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức - sự kiện.
        /// </summary>
        public static string NewsEvent_Title {
            get {
                return ResourceManager.GetString("NewsEvent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Note_Lang {
            get {
                return ResourceManager.GetString("Note_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tin khác.
        /// </summary>
        public static string Other_News {
            get {
                return ResourceManager.GetString("Other_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang này không tồn tại!.
        /// </summary>
        public static string PagenotFound_Lang {
            get {
                return ResourceManager.GetString("PagenotFound_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi xin lỗi, trang bạn yêu cầu không thể được tìm thấy!.
        /// </summary>
        public static string PageNotFoundMess_Lang {
            get {
                return ResourceManager.GetString("PageNotFoundMess_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác.
        /// </summary>
        public static string Partner_Title {
            get {
                return ResourceManager.GetString("Partner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quyền.
        /// </summary>
        public static string Permission_name_Lang {
            get {
                return ResourceManager.GetString("Permission_name_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập chức năng này!.
        /// </summary>
        public static string PermissionContent_Lang {
            get {
                return ResourceManager.GetString("PermissionContent_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string PhoneNumber_Lang {
            get {
                return ResourceManager.GetString("PhoneNumber_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        public static string Project_Title {
            get {
                return ResourceManager.GetString("Project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển dụng.
        /// </summary>
        public static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin này bắt buộc phải nhập.
        /// </summary>
        public static string Require_Message_Lang {
            get {
                return ResourceManager.GetString("Require_Message_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Search_Lang {
            get {
                return ResourceManager.GetString("Search_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu của bạn cho chúng tôi.
        /// </summary>
        public static string Send_Email_To_Us {
            get {
                return ResourceManager.GetString("Send_Email_To_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string Sender_Content {
            get {
                return ResourceManager.GetString("Sender_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email của bạn.
        /// </summary>
        public static string Sender_Email {
            get {
                return ResourceManager.GetString("Sender_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên người gửi.
        /// </summary>
        public static string Sender_Name {
            get {
                return ResourceManager.GetString("Sender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi server!.
        /// </summary>
        public static string ServerError_Lang {
            get {
                return ResourceManager.GetString("ServerError_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổ đông.
        /// </summary>
        public static string ShareHolder_Title {
            get {
                return ResourceManager.GetString("ShareHolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status_Lang {
            get {
                return ResourceManager.GetString("Status_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài khoản.
        /// </summary>
        public static string User_name_Lang {
            get {
                return ResourceManager.GetString("User_name_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập sai định dạng.
        /// </summary>
        public static string Validate_UserName_Invalid_Lang {
            get {
                return ResourceManager.GetString("Validate_UserName_Invalid_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện video.
        /// </summary>
        public static string Video_Gallery {
            get {
                return ResourceManager.GetString("Video_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string View_Lang {
            get {
                return ResourceManager.GetString("View_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng file bị lỗi!.
        /// </summary>
        public static string Wrong_file_format_Lang {
            get {
                return ResourceManager.GetString("Wrong_file_format_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can go to.
        /// </summary>
        public static string Youcangoto_Lang {
            get {
                return ResourceManager.GetString("Youcangoto_Lang", resourceCulture);
            }
        }
    }
}
