// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
	[Alias("ContentFavourite")]
    public partial class ContentFavourite : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public int ContentId { get; set; }
        [Required]
        public string ContentType { get; set; }
        [Required]
        public string Status { get; set; }
        [Required]
        public DateTime UpdatedTime { get; set; }
        [Required]
        public int UserId { get; set; }
        [Required]
        public string FavouriteType { get; set; }
    }

}
#pragma warning restore 1591
