// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
	[Alias("InvoiceImportDetail")]
    public partial class InvoiceImportDetail : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? InvoiceImportId { get; set; }
        public string ProductCode { get; set; }
        public int? ProductId { get; set; }
        public string CategoryCode { get; set; }
        public int? CategoryId { get; set; }
        public int? GroupId { get; set; }
        public string GroupCode { get; set; }
        public int? Quantity { get; set; }
        public double? Price { get; set; }
        public double? TotalMoney { get; set; }
        public double? Redure { get; set; }
        public DateTime? DateLimit { get; set; }
        public int? QuantityReturn { get; set; }
        public int? QuantityRemain { get; set; }
    }

}
#pragma warning restore 1591
