


















 


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `WebNews`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=KAANGKUN;Initial Catalog=web_news;Integrated Security=True;Persist Security Info=True;User ID=sa;Password=123456`
//     Schema:                 ``
//     Include Views:          `True`

//     Factory Name:          `SqlClientFactory`
 