


















 


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `WebNews`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=KAANGKUN;Initial Catalog=web_news;Integrated Security=True;Persist Security Info=True;User ID=sa;Password=123456`
//     Schema:                 ``
//     Include Views:          `True`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
}
#pragma warning restore 1591
