// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
	[Alias("Security_VwRoleService")]
    public partial class Security_VwRoleService 
    {
        [Required]
        public long RoleID { get; set; }
        public string RoleName { get; set; }
        public string FunctionName { get; set; }
        public int? FunctionID { get; set; }
        public string PermissionName { get; set; }
        public string IDInSystem { get; set; }
        public int? PermissionID { get; set; }
    }

}
#pragma warning restore 1591
