// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
	[Alias("System_User")]
    public partial class System_User : IHasId<int> 
    {
        [Alias("UserId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        [Required]
        public DateTime CreatedDate { get; set; }
        [Required]
        public string CreatedBy { get; set; }
        [Required]
        public int CreatedById { get; set; }
        [Required]
        public DateTime UpdatedDate { get; set; }
        [Required]
        public string UpdatedBy { get; set; }
        [Required]
        public int UpdatedById { get; set; }
        [Required]
        public string Salt { get; set; }
        public int? LoginFailedCount { get; set; }
        [Required]
        public string FullName { get; set; }
        public string Tel { get; set; }
        public string Image { get; set; }
        public int? UserType { get; set; }
        public short? UserRole { get; set; }
    }

}
#pragma warning restore 1591
