// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
	[Alias("System_Menu")]
    public partial class System_Menu : IHasId<int> 
    {
        [Alias("MenuId")]
        [Required]
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string Controller { get; set; }
        public string AliasUrl { get; set; }
        public int? Permission { get; set; }
        public string Text { get; set; }
        public int? MenuLevel { get; set; }
        public string Action { get; set; }
        public int? MenuOrder { get; set; }
        public string Description { get; set; }
        public bool? ShowMenu { get; set; }
        public string Area { get; set; }
    }

}
#pragma warning restore 1591
