// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
	[Alias("Vw_BizAccountType")]
    public partial class Vw_BizAccountType 
    {
        [Required]
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int? Status { get; set; }
        public string Description { get; set; }
        public string Group { get; set; }
        public string BizAccountCode { get; set; }
        public string BizAccountName { get; set; }
    }

}
#pragma warning restore 1591
