// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
	[Alias("Vw_InvoiceOutport")]
    public partial class Vw_InvoiceOutport 
    {
        [Required]
        public int Id { get; set; }
        public string Code { get; set; }
        public string UserName { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CustomerCode { get; set; }
        public DateTime? Date { get; set; }
        public double? Discount { get; set; }
        public bool? DiscountType { get; set; }
        public double? TotalMoney { get; set; }
        public double? VAT { get; set; }
        public double? SumMoney { get; set; }
        public double? PaidMoney { get; set; }
        public double? RemainMoney { get; set; }
        public int? Active { get; set; }
        public string Note { get; set; }
        public int? PayMethod { get; set; }
        public bool? IsComplete { get; set; }
        public int? TotalQuantity { get; set; }
        public int? Type { get; set; }
        public string BankCode { get; set; }
        public string CustomerName { get; set; }
        public double? TotalDeposit { get; set; }
        public double? TotalTransport { get; set; }
        public string InvoiceType { get; set; }
        public double? TotalDepositDiscount { get; set; }
        public string DeliveryAddress { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public double? TotalTransportDiscount { get; set; }
    }

}
#pragma warning restore 1591
