// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace webNews.Domain.Entities
{
	[Alias("Vw_Product")]
    public partial class Vw_Product 
    {
        [Required]
        public int Id { get; set; }
        public int? CategoryId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int? Quantity { get; set; }
        public int? Inventory { get; set; }
        public double? PriceInput { get; set; }
        public int? DiscountType { get; set; }
        public double? Discount { get; set; }
        public int? Status { get; set; }
        public string Description { get; set; }
        public string Solution { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string files { get; set; }
        public string Avatar { get; set; }
    }

}
#pragma warning restore 1591
